#Script to delpoy on the Render cloud platform

name: Node.js CI

on:
  push:
    braches: [main]
  pull_request:
    branches: [main]
  
jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env: 
        webhook_url: ${{secrets.DEPLOY_HOOK_URL}}
        webhook_secret: ${{secrets.DEPLOY_HOOK_KEY}}

    - uses: bounceapp/render-action@0.6.0
      with:
        render-token: ${{secrets.RENDER_API_KEY}}
        github-token: ${{secrets.ACC_API_KEY}}
        service-id: "srv-cggv2rkeooggmdfvs0n0"
        retries: 20
        wait: 16000
        sleep: 30000
        
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Install Dependencies
    #   run: npm install
  
    # - name: Run Tests
    #   run: npm acceptance_1
    #   run: npm acceptance_2
    #   run: npm acceptance_3

    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '12.x'
    - name: Run Tests

    - run: npm install
    # - run: npm run build --if-present
    # - run: npm run acceptance_1
    # - run: npm run acceptance_2
    - run: npm run acceptance_3
